# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/jupyter.ipynb.

# %% auto 0
__all__ = ['get_jupyter_content']

# %% ../../nbs/routes/jupyter.ipynb 2
import domolibrary.client.DomoAuth as dmda

# %% ../../nbs/routes/jupyter.ipynb 4
async def get_jupyter_content(
    auth: dmda.DomoAuth,
    content_path: str = "",
    debug_api: bool = False,
):
    url = f"https://{auth.domo_instance}.{auth.service_location}{auth.service_prefix}api/contents/{content_path}"

    res = await gd.get_data(
        url=f"{url}",
        method="GET",
        auth=auth,
        headers={"authorization": f"Token {auth.user_token}"},
        debug_api=debug_api,
        num_stacks_to_drop=1,
    )
    if not res.is_success:
        raise Exception("unable to retrieve content")

    return res
