name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  echosecrets:
    runs-on: windows-latest
    env:
      DOMO_USERNAME : ${{ secrets.DOMO_USERNAME}}
      DOJO_PASSWORD: ${{ secrets.DOJO_PASSWORD }}
      DOMO_DOJO_ACCESS_TOKEN: ${{ secrets.DOMO_DOJO_ACCESS_TOKEN }}
      DOMO_DOJO_USER_ID : ${{ secrets.DOMO_DOJO_USER_ID}}
    steps:
      - name: print github secrets
        run: |
          echo ${{secrets.DOMO_DOJO_ACCESS_TOKEN}} | sed 's/./& /g'
        
  test:
    runs-on: ubuntu-latest
    env:
      DOJO_PASSWORD: ${{ secrets.DOJO_PASSWORD }}
      DOMO_USERNAME : ${{ secrets.DOMO_USERNAME}}
      DOMO_DOJO_ACCESS_TOKEN: ${{ secrets.DOMO_DOJO_ACCESS_TOKEN }}
      DOMO_DOJO_USER_ID : ${{ secrets.DOMO_DOJO_USER_ID}}
      DOJO_DATASET_ID: ${{ secrets.DOJO_DATASET_ID }}
    steps:
      - uses: fastai/workflows/nbdev-ci@master
